export const getFileNameFromFirebaseUrl = (url: string) => {
  if (!url) {
    return "No url";
  }

  const parts = url.split("/");

  if (!parts.length) {
    return url;
  }

  const path = decodeURIComponent(parts[parts.length - 1].split("?")[0]);

  const uuidRegex =
    /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}-/;

  //remove attachemnt/ then remove the uuid generated by us and then the - before file name
  const fileName = path.replace("attachments/", "").replace(uuidRegex, "");

  return fileName;
};
